'''
Tasks Session 2 - Maellis R.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iXByHDUaJ4QEPHSuJ6cK1DcKBv0dO53
'''

#TASKS SESSION 2

#Task 1:  Write a program using a for loop to print the square of numbers from 1 to 8.
for x in range(1, 9):
  print(f"x square = {x ** 2}")


#Task 2: Define a function check_grades (grades) that: Takes a list of numbers(grades). For each grade, prints: "Pass" if the grade is 60 or more. "Fail" otherwise. Test it with a list of at least 5 grades.
def check_grades(grades):
  for grade in grades:
    if grade >= 60:
      print("Pass")
    else:
      print("Fail")

#Task 3: Write a function count_vowels(text) that counts the number of vowels (a, e, i, o, u) in a given string. Print the count and also print how many times each vowel appears. Your string: “It’s easy to lie with statistics. It’s hard to tell the truth without statistics.” Andrejs Dunkels
a='It’s easy to lie with statistics. It’s hard to tell the truth without statistics.'
def count_vowels(text):
  vowels = "aeiouAEIOU"
  counts = {v: 0 for v in vowels}
  for char in a:
    if char in counts:
      counts[char] += 1
      total = sum(counts.values())
  print(f"Total Vowel counts: {total}")
  for vowels, count in counts.items():
    print(f"{vowels}: {count}")
count_vowels(a)

#Task 4: You are designing a simple data collection tool where users keep entering numbers until they decide to stop. Skip empty inputs or non-numeric entries with a message like "Invalid input. Try again." Use a while loop.
Numbers = []
while True:
  entry = input("enter a number:")
  if entry.strip().lower()=="done":
    break
  if not entry.strip():
    print("Invalid input. Try again.")
    continue
  try:
    number = float(entry)
    Numbers.append(number)
  except ValueError:
    print("Invalid input. Try again.")

  print("Numbers entered:", Numbers)
  print("Total numbers entered:", len(Numbers))
  print("Sum of numbers entered:", sum(Numbers))


#Task 5: You are analyzing customer purchase data where each customer can make multiple purchases. The data is stored in a list of tuples like this [("Alice", 120), ("Bob", 80), ("Alice", 50), ("Bob", 20), ("Clara", 200)]
tuples = [("Alice", 120), ("Bob", 80), ("Alice", 50), ("Bob", 20), ("Clara", 200)]

customer_purchases = {}
for customer, purchase in tuples:
  if customer in customer_purchases:
    customer_purchases[customer] += [purchase]
  else:
    customer_purchases[customer] = [purchase]

for customer, purchases in customer_purchases.items():
  print(f"{customer} spent {customer_purchases[customer]} $.")
